name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: CertificatePass
    env:
      CERTIFICATE_PASS: ${{ secrets.PASSWORD }}
      TEST: 'abc'
      SOMEPASS: ${{secrets.PASS}}
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "environment variable is ${{ env.CERTIFICATE_PASS }}"
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: chmod +x "${{ github.workspace }}/demo.bat"
      - run: ${{github.workspace}}/demo.bat ${{secrets.PASSWORD}}
      - run: echo "sample var is ${{env.TEST}}"
      - run: echo "secret is ${{env.SOMEPASS}}"
